### ISSUE TITLE
Error connect local database

### ISSUE THREAD

**Issue by cicerocruz** [koles/gooddata-agent#2]
**I am not able to connect to my MSSQL 2014 database 

when I use jdbc/sqljdbc4.jar display this  error:
---------------------------------------------------------------------------------------------------------------------------------------------------
C:\GOODDATA\Agent>run

C:\GOODDATA\Agent>´╗┐rem Execu├º├úo do Agent.
'´╗┐rem' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\GOODDATA\Agent>echo In├¡cio do processo: 11:05:46,56
In├¡cio do processo: 11:05:46,56

C:\GOODDATA\Agent>java -Djava.io.tmpdir="./tmp" -jar agent-analytics-1.6.jar config.properties
 INFO [main] (Main.java:133) - InÝcio do processo do agent...

 INFO [main] (Main.java:134) - TOTVS Analytics: 1.6.2

mar 30, 2022 11:05:49 AM com.microsoft.sqlserver.jdbc.TDSChannel enableSSL
INFORMAÃıES: java.security path: C:\Program Files\Java\jre1.8.0_321\lib\security
Security providers: [SUN version 1.8, SunRsaSign version 1.8, SunEC version 1.8, SunJSSE version 1.8, SunJCE version 1.8, SunJGSS version 1.8, SunSASL version 1.8, XMLDSig version 1.8, SunPCSC version 1.8, SunMSCAPI version 1.8]
SSLContext provider info: Sun JSSE provider(PKCS12, SunX509/PKIX key/trust factories, SSLv3/TLSv1/TLSv1.1/TLSv1.2/TLSv1.3)
SSLContext provider services:
[SunJSSE: KeyPairGenerator.RSA -> sun.security.rsa.RSAKeyPairGenerator$Legacy
  aliases: [1.2.840.113549.1.1, OID.1.2.840.113549.1.1]
, SunJSSE: Signature.SHA1withRSA -> sun.security.rsa.RSASignature$SHA1withRSA
  aliases: [1.2.840.113549.1.1.5, 1.3.14.3.2.29, OID.1.2.840.113549.1.1.5]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunJSSE: SSLContext.TLS -> sun.security.ssl.SSLContextImpl$TLSContext
  aliases: [SSL]
, SunJSSE: SSLContext.TLSv1 -> sun.security.ssl.SSLContextImpl$TLS10Context
  aliases: [SSLv3]
, SunJSSE: Signature.MD2withRSA -> sun.security.rsa.RSASignature$MD2withRSA
  aliases: [1.2.840.113549.1.1.2, OID.1.2.840.113549.1.1.2]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunJSSE: KeyFactory.RSA -> sun.security.rsa.RSAKeyFactory$Legacy
  aliases: [1.2.840.113549.1.1, OID.1.2.840.113549.1.1]
, SunJSSE: Signature.MD5withRSA -> sun.security.rsa.RSASignature$MD5withRSA
  aliases: [1.2.840.113549.1.1.4, OID.1.2.840.113549.1.1.4]
  attributes: {SupportedKeyClasses=java.security.interfaces.RSAPublicKey|java.security.interfaces.RSAPrivateKey}
, SunJSSE: KeyStore.PKCS12 -> sun.security.pkcs12.PKCS12KeyStore
, SunJSSE: TrustManagerFactory.SunX509 -> sun.security.ssl.TrustManagerFactoryImpl$SimpleFactory
, SunJSSE: KeyManagerFactory.SunX509 -> sun.security.ssl.KeyManagerFactoryImpl$SunX509
, SunJSSE: TrustManagerFactory.PKIX -> sun.security.ssl.TrustManagerFactoryImpl$PKIXFactory
  aliases: [SunPKIX, X509, X.509]
, SunJSSE: KeyManagerFactory.NewSunX509 -> sun.security.ssl.KeyManagerFactoryImpl$X509
  aliases: [PKIX]
, SunJSSE: SSLContext.Default -> sun.security.ssl.SSLContextImpl$DefaultSSLContext
, SunJSSE: SSLContext.TLSv1.1 -> sun.security.ssl.SSLContextImpl$TLS11Context
, SunJSSE: Signature.MD5andSHA1withRSA -> sun.security.ssl.RSASignature
, SunJSSE: SSLContext.TLSv1.3 -> sun.security.ssl.SSLContextImpl$TLS13Context
, SunJSSE: SSLContext.TLSv1.2 -> sun.security.ssl.SSLContextImpl$TLS12Context
]
java.ext.dirs: C:\Program Files\Java\jre1.8.0_321\lib\ext;C:\WINDOWS\Sun\Java\lib\ext
ERROR [main] (Main.java:475) - Erro ao conectar no banco de dados

ERROR [main] (Main.java:477) - Status de execuþÒo: ERROR

C:\GOODDATA\Agent>echo Fim do processo: 11:05:49,97
Fim do processo: 11:05:49,97

When I use use jdbc/sqljdbc42.jar display this  error:
---------------------------------------------------------------------------------------------------------------------------------------------------

C:\GOODDATA\Agent>run

C:\GOODDATA\Agent>´╗┐rem Execu├º├úo do Agent.
'´╗┐rem' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.

C:\GOODDATA\Agent>echo In├¡cio do processo: 11:08:47,26
In├¡cio do processo: 11:08:47,26

C:\GOODDATA\Agent>java -Djava.io.tmpdir="./tmp" -jar agent-analytics-1.6.jar config.properties
 INFO [main] (Main.java:133) - InÝcio do processo do agent...

 INFO [main] (Main.java:134) - TOTVS Analytics: 1.6.2

ERROR [main] (Main.java:475) - Erro ao conectar no banco de dados

ERROR [main] (Main.java:477) - Status de execuþÒo: ERROR

C:\GOODDATA\Agent>echo Fim do processo: 11:08:49,33
Fim do processo: 11:08:49,33

C:\GOODDATA\Agent>pause
Pressione qualquer tecla para continuar. . .

**Comment by koles** [comment]
Hi Cícero, this repository is no longer maintained and supported, can you please repost your question, preferably in English, to https://github.com/gooddata/gooddata-agent?
